# _config.yml
title: Mobile Blog Test
description: Testing mobile-friendly Jekyll blog deployment
baseurl: "/mobile-blog"  # Change this to your repo name
url: "" # Update this with your GitHub Pages URL
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag