# _config.yml
title: Mobile Blog Test
description: Testing mobile-friendly Jekyll blog deployment
baseurl: "/mobile-blog"  # Change this to your repo name
url: "" # Update this with your GitHub Pages URL
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Gemfile
source "https://rubygems.org"

gem "jekyll", "~> 4.3.0"
gem "minima"
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]