title: Mobile Blog Test
description: Testing mobile-friendly Jekyll blog deployment
baseurl: "/mobile-blog"
url: ""
markdown: kramdown
theme: minima
future: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag